# Generated by Django 5.0.4 on 2024-07-22 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MeetingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=50)),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('building_code', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
                ('facility_description', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='classdata.classinfo')),
            ],
        ),
    ]
